# Generated by Django 2.1.5 on 2019-01-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
